const KEY='shy66_reset_v1';
const CORE_DAILY=new Set(['water','weigh','food','hygiene','sleep','mental','move','stretch']);
const mental=[['5-minute journal','Messy counts. Put whatever is loud in your head on the page.'],['3-minute slow breathing','No scrolling. Slow inhale, slower exhale.'],['Write 3 things that were not terrible','Low bar on purpose.'],['Listen to 2 songs intentionally','No scrolling while they play.'],['5-minute quiet reset','Meditate, lie down, or just sit quietly.'],['Mood + one-sentence reflection','Name the mood and write one sentence about it.'],['One-song nervous-system reset','Pick one calming song and do nothing else while it plays.'],['Brain dump: what can wait until tomorrow?','Move tomorrow-problems out of tonight’s brain.']];
const cleaning=[['Reset one laundry area','One small laundry-related zone only.'],['Clean one bathroom zone','Sink, mirror, shelf, or one tiny area.'],['Reset one kitchen section','Counter, sink, shelf, or another small section.'],['Reset one bedroom section','One surface, floor strip, or clutter pile.'],['Sweep, vacuum, or mop one area','One area is enough.'],['Do one cat-care cleaning task','Litter, bowls, or another cat-cleaning task.'],['Tiny deep-clean target','Pick one annoying little thing and finish only that.'],['Clear one doom-pile','Only one pile. Stop after it is contained.'],['Fridge or pantry mini-reset','Toss one expired thing or organize one small section.']];
const bonuses=['Take a 10-minute walk somewhere different','Try one nutritious food or drink choice','Clear one surface completely','Do 10 extra minutes of movement','Find one free activity you could do this week','Put your phone away for 30 minutes','Do one annoying real-life task before gaming','Find one free local event, hobby group, or friend option','Drink 8 bonus ounces of water','Do 5 minutes of posture work','Spend 10 minutes on a non-screen hobby experiment','Leave the apartment for something that is not an obligation','Prep one easy protein or produce option for later','Do a 10-minute music-only clean','Try a new walking route or staircase','Send one low-pressure social message','Do one thing future-you has been avoiding'];
const career=['Find 2 jobs you can genuinely apply for','Submit 1 quality application','Check your active application portals','Spend 20 minutes looking specifically for internships','Improve one resume bullet for a role you want','Save 3 roles worth applying to later'];
const socials=['Find one free event or class you could attend','Find one free hobby group that actually looks interesting','Try one free friend-making app or community','Make one small social move while you are already out','Message one person you genuinely want to talk to','Look for one free D&D, gaming, or hobby meetup option','Ask one person a low-pressure follow-up question','Spend 10 minutes browsing free local community events'];
const hobbies=['Try 10 minutes of a non-gaming hobby experiment','Draw, doodle, color, or design something for 10 minutes','Try one free beginner tutorial for a hobby you have never done','Do a tiny creative project using only things you already own','Spend 15 minutes learning a skill that is not school or work','Try a music, craft, writing, photo, or tabletop-related activity','Find one free hobby idea you would actually consider doing again','Make something small instead of only consuming content'];
const pep=['You do not need a perfect day. You need enough reps to keep the game moving.','Tiny wins still count as wins. Stack them.','You already started. That is the hardest part of most routines.','Boring consistency beats one dramatic perfect day.','Do the next quest, not the whole 66 days at once.','Progress does not have to look impressive to be real.','A weird day can still be a successful day.','You are allowed to win this in small, unimpressive-looking pieces.'];
const training=['30–40 min mostly walking + 6 × 5-second easy jogs with 2–3 min walking recovery.','35–45 min mostly walking + 8 × 5-second easy jogs with full walking recovery.','35–45 min + 6 × 10-second easy jogs with generous walking recovery.','40–45 min + 8 × 10-second easy jogs with generous walking recovery.','40–50 min + 6 × 15-second easy jogs if breathing stays controlled.','45–50 min + 8 × 15-second easy jogs if the prior stage felt manageable.','45–55 min + 6 × 20-second easy jogs only if the prior stage feels comfortable.','Practice your race-day walk/jog pattern and work toward the full 5K distance. Continuous running is not required.'];
const badgeDefs=[['first','First Rep','Complete your first quest.'],['five','Quest Gremlin','Complete 5 quests.'],['twentyfive','Momentum Machine','Complete 25 quests.'],['three','Three-Day Spark','Clear 3 days in a row.'],['seven','One-Week Menace','Clear 7 days in a row.'],['xp500','XP Hoarder','Reach 500 XP.'],['boss','Boss Slayer','Defeat a boss.'],['run3','Turkey Trot Trainee','Log 3 training sessions.'],['d14','Two-Week Reset','Reach Day 14.'],['d30','Thirty-Day Monster','Reach Day 30.'],['d66','Reset Complete','Finish Day 66.']];
const rewardIdeas=[['Perfume Sample Hunt','Hunt for a genuinely free perfume sample or one with no more than $3 shipping.'],['Coupon Goblin','Find a real online freebie or coupon that costs no more than $3 to receive.'],['Free Treat Quest','Pick one genuinely free treat: a sample, free event, library perk, app freebie, or promotion.'],['Tiny Upgrade','Use this token for a free sample or near-free upgrade that makes daily life a little more fun.']];
const bossDefs=[['Clutter Hydra','Finish 3 tiny cleaning zones in one session.','zones',3],['Scroll Goblin','Do a 60-minute phone-free offline block.','minutes',60],['Side-Quest Hoarder','Complete 3 bonus quests today.','bonus',3],['Procrastination Mimic','Complete the school, study, career, or early-admin quest before pressure time.','admin',1],['Couch Boss','Accumulate 45 minutes of intentional movement today.','move',45],['Boredom Dragon','Finish one required habit you normally abandon because it is boring.','proof',1]];
let section='today',taskTab='todo',state=load(),installPrompt=null;
function hash(n){let x=n|0;x=Math.imul(x^(x>>>16),0x45d9f3b);x=Math.imul(x^(x>>>16),0x45d9f3b);return (x^(x>>>16))>>>0}function pick(a,d,s,o=0){return a[hash(d*7919+s*104729+o*1543)%a.length]}
function fresh(){return{version:1,currentDay:1,viewedDay:1,xp:0,rewardXp:0,streak:0,bestStreak:0,totalDone:0,bossWins:0,badges:[],tokensEarned:0,tokensClaimed:0,trainingStage:1,trainingSuccesses:0,trainingSessions:0,postureSessions:0,custom:[],carryover:[],days:{},rewards:[],adaptation:[],randomSalt:Math.floor(Math.random()*1e9),lastSaved:null,startDate:new Date().toISOString().slice(0,10)}}
function emptyStats(){return{weight:'',steps:'',distance:'',water:'',mood:'',bedtime:'',wake:'',sleepQuality:'',saved:false}}function emptyMeas(){return{waist:'',hip:'',chest:'',thigh:'',saved:false}}
function load(){let s;try{s=JSON.parse(localStorage.getItem(KEY)||'null')}catch{}s=s||fresh();s={...fresh(),...s};s.days=s.days||{};s.custom=s.custom||[];s.rewards=s.rewards||[];s.adaptation=s.adaptation||[];Object.values(s.days).forEach(d=>migrateDay(d,s.randomSalt));if(!s.days['1'])s.days['1']=buildDay(s,1,'normal');return s}
function migrateDay(d,salt=1){d.stats={...emptyStats(),...(d.stats||{})};d.measurements={...emptyMeas(),...(d.measurements||{})};d.bossProgress=d.bossProgress||0;d.social=d.social||{title:pick(socials,d.day,salt,77),status:'todo',awarded:false};d.hobby=d.hobby||{title:pick(hobbies,d.day,salt,63),status:'todo',awarded:false};d.postureLogged=!!d.postureLogged;d.quests=(d.quests||[]).map(q=>({...q,category:q.category||'core'}))}
function save(){state.lastSaved=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(state));render()}
function addXP(n,msg){const oldLevel=Math.floor(state.xp/100)+1,oldTokens=state.tokensEarned;state.xp=Math.max(0,state.xp+n);if(n>0)state.rewardXp+=n;syncRewards();const newLevel=Math.floor(state.xp/100)+1;if(state.tokensEarned>oldTokens)showToast('Freebie Hunt token unlocked!');else if(newLevel>oldLevel)showToast(`Level ${newLevel} unlocked!`);else if(msg)showToast(msg)}
function removeEarnedXP(n){state.xp=Math.max(0,state.xp-n);state.rewardXp=Math.max(0,state.rewardXp-n);syncRewards()}
