function toggleCheck(id,cid){if(!editable())return;const q=quest(id),c=q?.checks?.find(x=>x.id===cid);if(!c)return;const was=q.status==='done',wasSkip=q.status==='skipped';c.done=!c.done;const now=q.checks.every(x=>x.done);if(now&&!was){if(wasSkip)refundSkipPenalty(q);q.status='done';state.totalDone++;addXP(q.xp,'Checklist cleared!')}else if(!now&&was){q.status='todo';removeEarnedXP(q.xp);state.totalDone=Math.max(0,state.totalDone-1)}save()}
function logWeightQuick(){if(!editable())return;const el=document.getElementById('quickWeight');const v=el?.value.trim();if(!v)return showToast('Enter your weight first.');const d=day(),first=!d.stats.saved;d.stats.weight=v;d.stats.saved=true;const q=quest('weigh');if(q&&q.status!=='done'){if(q.status==='skipped')refundSkipPenalty(q);q.status='done';state.totalDone++;addXP(q.xp,'Daily weigh-in logged +5 XP')}save()}
function saveStats(){if(!editable())return;const d=day();const weight=document.getElementById('stWeight').value.trim();if(!weight)return showToast('Weight is required for the daily log.');const first=!d.stats.saved;d.stats={weight,steps:val('stSteps'),distance:val('stDistance'),water:val('stWater'),mood:val('stMood'),bedtime:val('stBed'),wake:val('stWake'),sleepQuality:val('stSleepQ'),saved:true};const q=quest('weigh');if(first&&q&&q.status!=='done'){if(q.status==='skipped')refundSkipPenalty(q);q.status='done';state.totalDone++;addXP(q.xp,'Daily weight/stats logged +5 XP')}else showToast(first?'Daily log saved.':'Daily log updated.');save()}
function saveMeasurements(){if(!editable())return;const d=day(),first=!d.measurements.saved;d.measurements={waist:val('mWaist'),hip:val('mHip'),chest:val('mChest'),thigh:val('mThigh'),saved:true};if(first)addXP(15,'Measurement check-in saved +15 XP');else showToast('Measurements updated.');save()}
function setDayType(type){if(!editable())return;const old=day(),fresh=buildDay(state,state.currentDay,type);fresh.quests.forEach(n=>{const o=old.quests.find(x=>x.id===n.id);if(o){n.status=o.status;n.progress=o.progress;n.checks=o.checks}});fresh.stats=old.stats;fresh.measurements=old.measurements;fresh.trainingLogged=old.trainingLogged;fresh.trainingResult=old.trainingResult;fresh.trainingStageAtLog=old.trainingStageAtLog;fresh.bossDone=old.bossDone;fresh.bossProgress=old.bossProgress;fresh.social=old.social;fresh.hobby=old.hobby;fresh.postureLogged=old.postureLogged;fresh.recap=old.recap;state.days[String(state.currentDay)]=fresh;save()}
function trainingLog(kind){if(!editable()||day().trainingLogged)return;const d=day();d.trainingLogged=true;d.trainingResult=kind;d.trainingStageAtLog=state.trainingStage;state.trainingSessions++;if(kind==='manageable'){state.trainingSuccesses++;if(state.trainingSuccesses>=2&&state.trainingStage<training.length){state.trainingStage++;state.trainingSuccesses=0;showToast(`Turkey Trot stage advanced to ${state.trainingStage}!`)}}else if(kind==='hard')state.trainingSuccesses=0;const mv=quest('move');if(mv&&mv.status!=='done'){mv.status='done';mv.progress.current=Math.max(mv.progress.current,mv.progress.target);state.totalDone++;addXP(mv.xp)}addXP(10,'Training logged +10 XP');save()}
function postureLog(){if(!editable()||day().postureLogged)return;day().postureLogged=true;state.postureSessions++;addXP(10,'Posture side quest +10 XP');save()}
function bossStatus(){const b=bossFor(day().day);if(!b)return null;let cur=day().bossProgress;const kind=b[2],target=b[3];if(kind==='bonus')cur=day().quests.filter(q=>q.category==='bonus'&&q.status==='done').length;if(kind==='admin')cur=day().quests.filter(q=>['school','study','career','admin-early'].includes(q.id)&&q.status==='done').length;if(kind==='move')cur=quest('move')?.progress?.current||0;if(kind==='proof')cur=day().quests.some(q=>q.required&&q.status==='done')?1:0;return{def:b,current:cur,target,ready:cur>=target}}
function bossAdjust(delta){if(!editable())return;const st=bossStatus();if(!st||day().bossDone)return;day().bossProgress=Math.max(0,Math.min(st.target,day().bossProgress+delta));save()}
function defeatBoss(){if(!editable())return;const st=bossStatus();if(!st||!st.ready||day().bossDone)return;day().bossDone=true;state.bossWins++;addXP(50,`Boss defeated: ${st.def[0]} +50 XP!`);save()}
function sideAction(which,action){if(!editable())return;const obj=day()[which];if(action==='complete'){if(obj.status==='done')return;obj.status='done';if(!obj.awarded){obj.awarded=true;state.totalDone++;addXP(15,`${which==='social'?'Social':'Hobby'} side quest +15 XP`)}}else if(action==='skip'){if(obj.status==='done'&&obj.awarded){removeEarnedXP(15);state.totalDone=Math.max(0,state.totalDone-1);obj.awarded=false}obj.status='skipped'}else if(action==='reroll'&&obj.status==='todo'){const pool=which==='social'?socials:hobbies;const idx=pool.indexOf(obj.title);obj.title=pool[(idx+1+hash(state.currentDay+state.randomSalt+(which==='social'?0:17))%3)%pool.length]}save()}
function finishDay(){if(!editable())return;const d=day(),req=d.quests.filter(q=>q.required),done=req.filter(q=>q.status==='done').length,pct=req.length?done/req.length:0;d.finished=true;d.clearPct=pct;d.cleared=pct>=.7;const carry=d.quests.filter(q=>q.required&&q.status!=='done'&&!CORE_DAILY.has(q.id)).map(q=>q.title).slice(0,2);state.carryover=carry;if(d.cleared){state.streak++;state.bestStreak=Math.max(state.bestStreak,state.streak);addXP(25,'Day cleared. Streak protected +25 XP!')}else{state.streak=0;showToast('Day closed. No restart required — tomorrow is the next round.')}syncRewards();const earned=d.quests.filter(q=>q.status==='done').reduce((n,q)=>n+q.xp,0)+(d.measurements.saved?15:0)+(d.trainingLogged?10:0)+(d.bossDone?50:0)+(d.social.awarded?15:0)+(d.hobby.awarded?15:0)+(d.postureLogged?10:0)+(d.cleared?25:0);d.recap={xpEarned:earned,requiredDone:done,requiredTotal:req.length,bonusDone:d.quests.filter(q=>!q.required&&q.status==='done').length,clearPct:Math.round(pct*100),cleared:d.cleared,carryover:carry,message:d.cleared?'You did enough. That is the point.':'No restart required. Tomorrow is just the next round.'};if(state.currentDay%7===0)state.adaptation.push({day:state.currentDay,tier:tier(),clearRate:recentRate(),reason:tier()>0?'Recent completion supports a gentle increase.':'Targets held steady because consistency matters more than escalation.'});if(state.currentDay<66){state.currentDay++;state.viewedDay=state.currentDay;if(!state.days[String(state.currentDay)])state.days[String(state.currentDay)]=buildDay(state,state.currentDay,'normal')}save()}
function viewDay(delta){const n=Math.max(1,Math.min(state.currentDay,state.viewedDay+delta));state.viewedDay=n;save()}
function weekly(){const ds=Object.values(state.days).filter(d=>d.finished).sort((a,b)=>b.day-a.day).slice(0,7),req=ds.reduce((n,d)=>n+d.quests.filter(q=>q.required).length,0),done=ds.reduce((n,d)=>n+d.quests.filter(q=>q.required&&q.status==='done').length,0),moods=ds.map(d=>+d.stats.mood).filter(Boolean);return{days:ds.length,clear:ds.filter(d=>d.cleared).length,completion:req?Math.round(done/req*100):0,avgMood:moods.length?(moods.reduce((a,b)=>a+b,0)/moods.length).toFixed(1):'—'}}
function sleepShift(){const logs=Object.values(state.days).filter(d=>d.stats.saved&&d.stats.bedtime).sort((a,b)=>b.day-a.day).slice(0,3);if(logs.length<3)return{n:logs.length,text:'Log bedtime for 3 days first. Then the app will start giving a gentle 15-minute earlier nudge.'};const mins=logs.map(d=>timeToMinutes(d.stats.bedtime)),avg=Math.round(mins.reduce((a,b)=>a+b,0)/mins.length),target=(avg-15+1440)%1440;return{n:logs.length,text:`Your recent bedtime baseline is about ${minutesToTime(avg)}. Try starting wind-down around ${minutesToTime(target)}. Do not force an early wake if you are sleep-deprived.`}}
function timeToMinutes(s){if(!s)return 0;let[h,m]=s.split(':').map(Number);return h*60+m}function minutesToTime(m){let h=Math.floor(m/60)%24,min=m%60,amp=h>=12?'PM':'AM',hh=h%12||12;return `${hh}:${String(min).padStart(2,'0')} ${amp}`}
function claimReward(){const available=state.tokensEarned-state.tokensClaimed;if(available<=0)return;state.tokensClaimed++;const [title,description]=pick(rewardIdeas,state.currentDay,state.randomSalt,state.tokensClaimed*19);state.rewards.unshift({id:'r'+Date.now(),day:state.currentDay,title,description,claimedAt:new Date().toISOString(),note:''});showToast(`Reward unlocked: ${title}`);save()}
function saveRewardNote(id){const r=state.rewards.find(x=>x.id===id),el=document.getElementById('rewardNote-'+id);if(r&&el){r.note=el.value;save()}}
